spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_journal_auth
    username: root
    password: jy6zi84013
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: DEBUG
