# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_journal_auth
    username: root
    password: jy6zi84013
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt:
  secret: secretKey
  expirationMs: 86400000

# Server Port (Optional)
server:
  port: 8080